### ISSUE TITLE
大佬,请教一下。

### ISSUE THREAD

**Issue by leommjj** [coriger/siyuan-video-extension#1]
我想移植到油猴脚本上，这样ipad上也能用；目前写好了获取时间戳的脚本，就是跳转的话要解决一个标签页之间通信的问题、

**Comment by coriger** [comment]
> 我想移植到油猴脚本上，这样ipad上也能用；目前写好了获取时间戳的脚本，就是跳转的话要解决一个标签页之间通信的问题、

插件这里是通过background.js进行跨标签页通信的，请求从思源页面的content.js发出，发到background.js，然后执行一些业务逻辑，比如查找时间戳对应的视频是否在浏览器打开，如果没打开就新建一个tab页跳转，如果已存在就往这个tab页发送跳转时间戳的指令，这样视频页的content.js接受到跳转指令就可以执行跳转逻辑，大概就这么个机制，你看看油猴里面有没有相关的通信api完成上面类似的功能
